spring.application.name=Comanda-Digital

# Porta Dinâmica (VITAL para o Render)
server.port=${PORT:8080}

# Banco de Dados Dinâmico
# Se existir a variável no Render, ele usa. Se não, usa o localhost (para você testar em casa)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/comanda_digital}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:iBeus2024}

# Hibernate e JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Removi o Dialect fixo para o Hibernate 6 detectar sozinho o MySQL do Aiven
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Documentação da API (Swagger)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html